mongodb:
  URL: "mongodb://admin:pzj20162116@localhost:27017/?authSource=admin&replicaSet=rs0"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "pzj20162116"
  MONGO_INITDB_DATABASE: "stellux"
  MONGO_USERNAME: "codepzj"
  MONGO_PASSWORD: "pzj20162116"

server:
  PORT: 9001
