services:
  mongo:
    container_name: mongo
    image: mongo:8.0
    env_file:
      - ../config/stellux.yaml
    volumes:
      - ./data/mongo_data/db:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongo/keyFile:/data/mongodb/keyFile
    ports:
      - "27017:27017"
    networks:
      - stellux-network
    restart: always
    command: --auth --bind_ip_all --replSet rs0 --keyFile /data/mongodb/keyFile

networks:
  stellux-network:
    name: stellux-network
    driver: bridge