name: Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Get dependencies
      run: |
        cd server
        go mod download

    - name: Build
      working-directory: server
      run: go build -v ./...

    - name: Test
      working-directory: server
      run: go test -v ./...
